from pathlib import Path
from textwrap import wrap

from PIL import Image, ImageChops


def main():
    src = Image.open("04b_03b.png").convert("L")
    src = ImageChops.invert(src)
    glyphs = [0]
    for o in range(33, 128):
        x = (o & 15) << 3
        y = ((o & 0xf0) >> 1) - 16
        img = src.crop((x, y, x+8, y+8))
        l, t, r, b = img.getbbox()
        w = r - l
        h = b - 1
        assert l == 0
        assert t >= 1
        assert 0 < w <= 6
        assert 0 < h <= 6
        img = img.crop((0, 1, 6, 7))
        assert img.size == (6, 6)
        v = 0
        for x in range(img.width-1, -1, -1):
            for y in range(img.height-1, -1, -1):
                v <<= 1
                if img.getpixel((x, y)):
                    v |= 1
        glyphs.append(v)

    img = Image.open("examples/arrows.png")
    for i in range(4):
        v = 0
        for j in range(4, -1, -1):
            x = i * 6 + j
            for y in range(5, -1, -1):
                v <<= 1
                if img.getpixel((x, y)):
                    v |= 1
        glyphs.insert(-1, v)

    glyphs = "\n\t\t".join(wrap(", ".join(map(str, glyphs)), width=70))

    scriptpath = Path(__file__)
    topdir = scriptpath.parent
    while True:
        if (gomodpath := topdir / "go.mod").is_file():
            break
        nexttopdir = topdir.parent
        if nexttopdir == topdir:
            raise RuntimeError("go.mod not found")
        topdir = nexttopdir

    script = scriptpath.relative_to(topdir)

    check, module, _ = gomodpath.read_text().split(maxsplit=2)
    assert check == "module"
    _, _, package = module.rpartition("/")

    print(f"""\
// generated by {script}; DO NOT EDIT.

package {package}

// Face04B03B is a Face based on the 04B-03B TrueType font by Yuji Oshimoto
// (http://www.dsg4.com/04/).
//
// At the moment, it holds the printable characters in ASCII starting with
// space, and the Unicode replacement character U+FFFD.  Most glyphs are 5
// pixels wide by 6 pixels high, though some are narrower and some descend
// further.
//
// Its data is entirely self-contained and does not require loading from
// separate files.
var Face04B03B = &Face56vw{{
	Ascent:  5,
	Descent: 2,
	XHeight: 3,
	Glyphs: []Glyph56vw{{
		{glyphs},
	}},
	Ranges: []Range{{
		R(' ', 127, 0),
		R('\\u2190', '\\u2194', 95),
		R('\\ufffd', '\\ufffe', 99),
	}},
}}""")


if __name__ == "__main__":
    main()
