// generated by 04b_03b/png2go.py; DO NOT EDIT.

package microfont

// Face04B03B is a Face based on the 04B-03B TrueType font by Yuji Oshimoto
// (http://www.dsg4.com/04/).
//
// At the moment, it holds the printable characters in ASCII starting with
// space, and the Unicode replacement character U+FFFD.  Most glyphs are 5
// pixels wide by 6 pixels high, though some are narrower and some descend
// further.
//
// Its data is entirely self-contained and does not require loading from
// separate files.
var Face04B03B = &Face56vw{
	Ascent:  5,
	Descent: 2,
	XHeight: 3,
	Glyphs: []Glyph56vw{
		0, 23, 12291, 175941578, 3503958, 426263251, 74536287, 3, 1102, 913,
		20613, 17284, 1056, 16644, 16, 17318416, 8197215, 1985, 6116701,
		8213845, 8159759, 7689559, 7427423, 808513, 8213855, 8213831, 10, 26,
		70276, 41610, 17041, 1856833, 257283167, 8147295, 7435615, 4527199,
		3740767, 5592415, 1331551, 7689311, 8143135, 71633, 8197144, 7094559,
		4260895, 520482911, 8143007, 8197215, 3969631, 8229983, 6148447,
		7689559, 6081, 8193055, 836623, 524416031, 7094555, 8209687, 5068121,
		1119, 270549121, 2001, 8258, 4260880, 129, 7423256, 7423262, 83228,
		7947548, 5358860, 2664328, 7554332, 7356702, 26, 58, 5276190, 30,
		470925596, 7356700, 7423260, 7423292, 15811868, 16668, 5326612, 83844,
		7406620, 3212300, 474072092, 82452, 15795228, 5358868, 71364, 31,
		18129, 270402, 355029653,
	},
	Ranges: []Range{
		R(' ', 127, 0),
		R('\ufffd', '\ufffe', 95),
	},
}
