// generated by 04b_08/png2go.py; DO NOT EDIT.

package microfont

// Face04B08 is a Face based on the 04B-08 TrueType font by Yuji Oshimoto
// (http://www.dsg4.com/04/).
//
// At the moment, it holds the printable characters in ASCII starting with
// space, and the Unicode replacement character U+FFFD.  Most glyphs are 6
// pixels square, though some are narrower and one is wider.
//
// Its data is entirely self-contained and does not require loading from
// separate files.
var Face04B08 = &Face55vw{
	Ascent:  5,
	Descent: 1,
	Glyphs: []Glyph55vw{
		0, 736, 3075, 11512810, 31129271, 27070835, 680384187, 3, 558, 465,
		5189, 4357252, 24, 4329604, 16, 1118480, 15255086, 17393, 24827581,
		33216181, 9413964, 31119031, 31119039, 3319329, 33216191, 33216183,
		10, 26, 17732, 10824010, 4433, 7525409, 33224255, 32675007, 11196095,
		18400831, 15255103, 22730431, 5412031, 31118911, 32641183, 18417,
		16303624, 18157727, 17318431, 32575583, 32772191, 33080895, 7509183,
		33343039, 25072831, 31119031, 1113121, 33047071, 7618823, 16268815,
		18157905, 3301507, 18470705, 575, 17043521, 1009, 2082, 17318416, 65,
		18276, 31, 4977, 34850, 22369621,
	},
	Ranges: []Range{
		R(' ', 'a', 0),
		R('a', 'z'+1, int('A'-' ')), // map lowercase runes to uppercase glyphs
		R('z'+1, 127, 65),
		R('\ufffd', '\ufffe', 69),
	},
}
