// generated by 04b_03/png2go.py; DO NOT EDIT.

package microfont

// Face04B03 is a Face based on the 04B-03 TrueType font by Yuji Oshimoto
// (http://www.dsg4.com/04/).
//
// At the moment, it holds the printable characters in ASCII starting with
// space, and the Unicode replacement character U+FFFD.  Most glyphs are 5
// pixels wide by 6 pixels high, though some are narrower and some descend
// further.
//
// Its data is entirely self-contained and does not require loading from
// separate files.
var Face04B03 = &Face56vw{
	Ascent:  5,
	Descent: 2,
	XHeight: 4,
	Glyphs: []Glyph56vw{
		0, 23, 12291, 175941578, 2864532, 269239809, 337728842, 3, 1102, 913,
		20613, 17284, 1056, 16644, 16, 17318416, 3740750, 1985, 4805977,
		2708817, 2224780, 2446679, 2184526, 808513, 2708810, 3757378, 10, 26,
		70276, 41610, 17041, 546113, 240505934, 7901790, 2708831, 70734,
		3740767, 87391, 20831, 7689294, 8143135, 71633, 4002824, 4497695,
		66591, 520634527, 8143007, 3740750, 1610335, 12129358, 5804639,
		2446674, 6081, 3998735, 836623, 255910927, 7094555, 4015363, 79193,
		1119, 270549121, 2001, 8258, 4260880, 129, 7939212, 3220639, 74892,
		8201356, 1140364, 22404, 8039044, 7348383, 29, 1888, 4768287, 31,
		470409374, 7348382, 3220620, 3220670, 16327820, 8478, 2729364, 74690,
		7930894, 1606670, 106980870, 74514, 8030726, 4810386, 71364, 31,
		18129, 270402, 355029653,
	},
	Ranges: []Range{
		R(' ', 127, 0),
		R('\ufffd', '\ufffe', 95),
	},
}
